# -*- coding: utf-8 -*-
"""crawling3_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_rPdWwU9qBRP8yjLBmU1PZ4bvgzI5BQY
"""

import time
from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome('./chromedriver')
time.sleep(5)
driver.get('https://www.imdb.com/title/tt4154796/reviews?ref_=tt_ov_rt')

driver.find_element_by_xpath('//*[@id="load-more-trigger"]').click()
time.sleep(10)

driver.find_element_by_xpath('//*[@id="load-more-trigger"]').click()
time.sleep(10)

driver.find_element_by_xpath('//*[@id="load-more-trigger"]').click()
time.sleep(10)

click_list = driver.find_elements_by_xpath("//div[@class='expander-icon-wrapper show-more__control']")

for click in click_list:
    if click.is_displayed():
        click.click()

req = driver.page_source
bs = BeautifulSoup(req, 'lxml')

title_list = bs.findAll('a', 'title')

for title in title_list:
    print(title.getText())
    
review_list = bs.findAll('div', 'text show-more__control')

for content in review_list:
    print(content.getText()+"\n")

score_list = bs.findAll('span', 'rating-other-user-rating')

for score in score_list:
    print(score.span.getText())

import re

def clean_str(string):
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"\'s", " \'s", string)
    string = re.sub(r"\'ve", " \'ve", string)
    string = re.sub(r"n\'t", " n\'t", string)
    string = re.sub(r"\'re", " \'re", string)
    string = re.sub(r"\'d", " \'d", string)
    string = re.sub(r"\'ll", " \'ll", string)
    string = re.sub(r",", " , ", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", " \( ", string)
    string = re.sub(r"\)", " \) ", string)
    string = re.sub(r"\?", " \? ", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()

with open('./review.txt', 'w', encoding='UTF-8') as f:
    for i in range(len(title_list)):
        line = clean_str(title_list[i].getText())
                         +" "+clean_str(review_list[i].getText())+"\n"
        f.write(line)

with open('./score.txt', 'w', encoding='UTF-8') as f:
    for i in range(len(score_list)):
        line = score_list[i].span.getText()+"\n"
        f.write(line)

