# -*- coding: utf-8 -*-
"""python_basic4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19n_pJBpsmVhUFWzLUR_-gga1PsDkKWDR
"""

## Class
class Flight:
    pass
    
f = Flight()
print(type(f))

## 메소드 
class Flight:
    def number(self):
        return 'KE081'

f = Flight()
print(f.number())

## 생성자(new) & 초기화자(init) & 메소드 
class Flight:
    def __init__(self):
        print('init')
        super().__init__()
    def __new__(cls):
        print('new')
        return super().__new__(cls)
    def number(self):
        return 'KE081'

f = Flight()

## 초기화
class Flight:
    def __init__(self, number):
        self._number = number 
    def number(self):
        return self._number 

f = Flight('KE082')
print(f.number())
print(f._number)

## 유효성 검증 
class Flight:
    def __init__(self, number):
        if not number[:2].isalpha():
            raise ValueError("첫 두 글자가 알파벳이 아닙니다.")
        if not number[:2].isupper():
            raise ValueError("첫 두 글자가 대문자가 아닙니다.")
        if not number[2:].isdigit():
            raise ValueError("세번째 글자 이상이 양의 숫자가 아닙니다.")
        self._number = number 
    def number(self):
        return self._number 

# f = Flight('Ke082')
# f = Flight('KEE82')
f = Flight('0KE082')

## 더블 언더바 
class Flight:
    def __init__(self, number):
        if not number[:2].isalpha():
            raise ValueError("첫 두 글자가 알파벳이 아닙니다.")
        if not number[:2].isupper():
            raise ValueError("첫 두 글자가 대문자가 아닙니다.")
        if not number[2:].isdigit():
            raise ValueError("세번째 글자 이상이 양의 숫자가 아닙니다.")
        self.__number = number
    def number(self): 
        return self.__number 

f = Flight('KE082')
print(f.number())
f.__number = 'KE081'
print(f.number())

class IRIS:
  def __init__(self,student):
    if not student[:2].isalpha():
      raise ValueError("첫 두 글자가 알파벳이 아니다.")
    self.__student=student
  def student1(self):
    return self.__student

iris = IRIS("aw1234")
print(iris.student1())

f = Flight('KE082')
print(f.number())
f.__number = 'KE081'
print(f.number())

## 인스턴스 속성 (변수)
class Flight:
    def __init__(self, number, passenger_num):
        self.__number = number 
        self._passenger_num = passenger_num

    def number(self,number):
        self.__number = number
        return self.__number
        
    def add_passenger(self, num):
        self._passenger_num += num

f1 = Flight('KE082', 0) # 클래스 객체 생성 및 변수에 할당 
f2 = Flight('KE081', 0)
f1.add_passenger(2)
f2.add_passenger(3)
print(f1.number("kimjungin"))
print(f1._passenger_num)
print(f2._passenger_num)

## 클래스 속성 
class Flight: 
    nation = 'Korea'
    def __init__(self, number, passenger_num):
        self.__number = number 
        self._passenger_num = passenger_num

f1 = Flight('KE082', 0)
f2 = Flight('KE081', 1)
print(f1.nation)
print(f2.nation)
f1._passenger_num