# -*- coding: utf-8 -*-
"""Test using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VK2qUqb5IbiOauz3cHa3wDBBTRCTKgKj

1.홀수, 짝수를 구분하는 코드를 작성해봅시다
"""

num=5

if num%2==0:
  print("짝수입니다.")
else:
  print("홀수입니다.")

"""2.get_special_students()함수를 정의하시오."""

student2score= {
    "Darius":100,
    "Dr.Mundo":80,
    "Morgana":60,
    "Sivir":75,
    "Yummi":20,
    "Viktor":97
}

def get_special_students(student2score):
  special_students=[]
  for i in student2score.keys():
    if student2score[i] >= 80:
      special_students.append(i)
  return special_students

get_special_students(student2score)

"""3.딕셔너리 생성 및 리턴 """

text = "Apple is fruit. Orange is also fruit. Tomato is fruit?"

def word_index_count(text):
  id=0
  text=text.lower()
  text=text.replace(".","")
  text=text.replace("?","")  
  word_id={}
  id_frequency={}
  text_split=set(text.split(" "))
  
  for names in text_split:
    id+=1
    word_id[names]=id
    id_frequency[id]=text.split(" ").count(names)
  
  return word_id,id_frequency

result_id,result_frequency=word_index_count(text)
print(result_id,"\n",result_frequency)

"""4.모형 출력"""

blank_n=4
star_n=1

for i in range(5):
  print(" "*blank_n,"*"*star_n)
  blank_n-=1
  star_n+=2